[package]
name = "gengine"
version = "0.1.0"
authors = ["Phillip Chang <lasagnaphil@snu.ac.kr>"]

[dependencies]
sdl2 = "0.31.0"
gl = "0.6.0"
libc = "0.2"
cgmath = "0.16.0"
stb_image = "0.2.2"
rand = "0.4"
derivative = "1.0.0"
find_folder = "0.3.0"
